language: bash
sudo: required
dist: bionic
env:
- OS=ubuntu ARCH=amd64 DIST=bionic
- OS=debian ARCH=amd64 DIST=buster
- OS=debian ARCH=armhf DIST=buster QEMU=qemu-user-static
- OS=debian ARCH=armel DIST=buster QEMU=qemu-user-static
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository --yes ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes debhelper pbuilder-ev3dev gobject-introspection $QEMU
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-$DIST
- curl -L https://github.com/ev3dev/grx/archive/ev3dev-$DIST.tar.gz | tar --strip-components=1 -xz grx-ev3dev-$DIST/debian
script:
- pbuilder-ev3dev dev-build
